### ISSUE TITLE
feature request: need heat map graph

### ISSUE THREAD

**Issue by ruru-m07** [greengem/tracktive#2]
# @greengem  we want heat map graph support.

## like this

![Screenshot 2024-02-03 110645](https://github.com/greengem/tracktive/assets/142723369/6e22f463-c43e-4379-9850-f6c9e8aa7950)

**Comment by greengem** [comment]
@ruru-m07  Working on it now.

**Comment by ruru-m07** [comment]
> @ruru-m07 Working on it now. Are you a dev or user?

@greengem i'm a new learner.

**Comment by greengem** [comment]
closing this issue since I think you confused my library with https://github.com/uiwjs/react-heat-map/releases

**Comment by greengem** [comment]
closing this issue since I think you confused my library with https://github.com/uiwjs/react-heat-map/releases
